kind: Pod
apiVersion: v1
metadata:
  name: nginx-pod #name of the pod
  namespace: nginx
spec:
  containers:
    - name: nginx #name of container
      image: nginx:latest
      ports:
        - containerPort: 80
